fff

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1,5 +1,7 @@
 version: '3.9'
 
+# For usage instructions please take a look at the README.md file.
+
 volumes:
   chainweb-config: {}
   chainweb-db: {}
@@ -8,20 +10,32 @@ services:
 
   # ########################################################################## #
   # Database Initialization
-
-  chainweb-initialize-db-sync:
-    container_name: chainweb-initialize-db-sync
+  chainweb-initialize-db:
+    container_name: chainweb-initialize-db
     image: larsk/rsync
     profiles:
     - initialize-db
     volumes:
     - chainweb-db:/db:rw
     environment:
+      KADENA_NETWORK: ${KADENA_NETWORK:-mainnet01}
       SERVER: ${DB_SYNC_SERVER:-us-w1.chainweb.com}
     entrypoint: "/bin/sh"
     command:
     - "-c"
     - |
+      case "$$KADENA_NETWORK" in
+        mainnet01)
+          echo "SERVER=$${SERVER:=us-w1.chainweb.com}"
+          ;;
+        testnet04)
+          echo "SERVER=$${SERVER:=us1.testnet.chainweb.com}"
+          ;;
+        *)
+          echo "unknown or unsupported chainweb version: $$KADENA_NETWORK" 1>&2
+          exit 1
+      esac
+
       mkdir -p "/db/0"
       rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
       rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
@@ -29,24 +43,76 @@ services:
       rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
 
   # ########################################################################## #
-  chainweb-initialize-db-config:
-    container_name: chainweb-initialize-db-config
+  # Database Validation
+
+  # Optional (can be used instead of chainweb-db-initialize
+  # Shut down chainweb-node before running this.
+  chainweb-valiate-db-sync:
+    container_name: chainweb-validate-db-sync
+    image: larsk/rsync
+    profiles:
+    - validate-db
+    volumes:
+    - chainweb-db:/db:rw
+    environment:
+      KADENA_NETWORK: ${KADENA_NETWORK:-mainnet01}
+      SERVER: ${DB_SYNC_SERVER:-us-w1.chainweb.com}
+    entrypoint: "/bin/sh"
+    command:
+    - "-c"
+    - |
+      case "$$KADENA_NETWORK" in
+        mainnet01)
+          echo "SERVER=$${SERVER:=us-w1.chainweb.com}"
+          ;;
+        testnet04)
+          echo "SERVER=$${SERVER:=us1.testnet.chainweb.com}"
+          ;;
+        *)
+          echo "unknown or unsupported chainweb version: $$KADENA_NETWORK" 1>&2
+          exit 1
+      esac
+
+      mkdir -p "/db/0"
+      rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
+      rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
+      rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
+      rsync -avz --delete "rsync://$${SERVER}/db/0/rocksDb" "/db/0/"
+
+  chainweb-validate-db-config:
+    container_name: chainweb-validate-db-config
     image: alpine:latest
+    environment:
+      KADENA_NETWORK: ${KADENA_NETWORK:-mainnet01}
     volumes:
     - chainweb-config:/config:rw
     entrypoint: "/bin/sh"
     profiles:
-    - initialize-db
+    - validate-db
     command:
     - "-c"
     - |
-      cat > /config/chainweb-initialize-db-config.yaml <<EOF
+      cat > /config/chainweb-validate-db-config.yaml <<EOF
       databaseDirectory: /chainweb/db
       chainweb:
+        version: ${KADENA_NETWORK}
         allowReadsInLocal: true
         headerStream: true
         throttling:
           global: 1000
+        p2p:
+          peer:
+            interface: localhost
+            hostaddress:
+              port: 4445
+          private: true
+          ignoreBootstrapNodes: true
+        transactionIndex:
+          enabled: false
+        mempoolP2p:
+          enabled: false
+        cuts:
+          pruneChainDatabase: headers-checked
       logging:
         telemetryBackend:
           enabled: true
@@ -83,42 +149,48 @@ services:
           default: error
       EOF
 
-  # ########################################################################## #
-  chainweb-initialize-db:
-    container_name: chainweb-initialize-db
+  # Shut down chainweb-node before running this.
+  chainweb-validate-db:
+    container_name: chainweb-validate-db
     restart: "no"
-    image: ghcr.io/kadena-io/chainweb-node/ubuntu:latest
+    image: ${IMAGE:-ghcr.io/kadena-io/chainweb-node/ubuntu:latest}
+    environment:
+      KADENA_NETWORK: ${KADENA_NETWORK:-mainnet01}
     stop_signal: SIGINT
     profiles:
-    - initialize-db
+    - validate-db
     ulimits:
       nofile:
         soft: 65535
         hard: 65535
     depends_on:
-      chainweb-initialize-db-sync:
-        condition: "service_completed_successfully"
-      chainweb-initialize-db-config:
+      chainweb-validate-db-config:
         condition: "service_completed_successfully"
     volumes:
     - chainweb-db:/chainweb/db:rw
     - chainweb-config:/config:ro
-    entrypoint:
-    - /chainweb/chainweb-node
+    entrypoint: /bin/bash
     command:
-    - +RTS
-    - -T
-    - -RTS
-    - --config-file=/config/chainweb-initialize-db-config.yaml
-    - --chainweb-version=${NETWORK:-mainnet01}
-    - --log-handle=stderr
+    - "-c"
+    - |
+      [ -d "/chainweb/db/0/rocksDb" ] || { echo "missing database. Try running chainweb-validate-db-sync first" 1>&2; exit 1; }
+      rm -rf "/db/0/sqlite/*"
+      /chainweb/chainweb-node \
+        +RTS \
+        -T \
+        -H1G \
+        -RTS \
+        --config-file=/config/chainweb-validate-db-config.yaml \
+        --log-handle=stderr
 
   # ########################################################################## #
   # Chainweb Node
 
   chainweb-node:
     container_name: chainweb-node
-    image: ghcr.io/kadena-io/chainweb-node/ubuntu:latest
+    image: ${IMAGE:-ghcr.io/kadena-io/chainweb-node/ubuntu:latest}
+    environment:
+      KADENA_NETWORK: ${KADENA_NETWORK:-mainnet01}
     restart: unless-stopped
     stop_grace_period: "20s"
     stop_signal: SIGINT
@@ -129,11 +201,11 @@ services:
     ports:
     - mode: host
       protocol: tcp
-      published: 1789
+      published: ${P2P_PORT:-1789}
       target: 1789
     - mode: host
       protocol: tcp
-      published: 1848
+      published: ${SERVICE_PORT:-1848}
       target: 1848
     volumes:
     - chainweb-db:/chainweb/db:rw
@@ -154,12 +226,13 @@ services:
     - -H1G
     - -RTS
     - --header-stream
-    - --prune-chain-database=none
     - --database-directory=/chainweb/db
-    - --chainweb-version=${NETWORK:-mainnet01}
+    - --chainweb-version=${KADENA_NETWORK:-mainnet01}
     - --log-level=warn
-    - --log-handle=stderr
+    - --log-handle=stdout
+    - --log-format=json
     - --telemetry-log-handle=stderr
+    - --telemetry-log-format=json
     - --p2p-port=1789
     healthcheck:
       interval: "1m"
@@ -247,7 +320,5 @@ services:
     image: alpine:latest
     entrypoint:
     - /bin/sh
-    volumes:
-    - chainweb-db:/db:ro
     profiles:
     - debug
